#!/usr/bin/python3
# -*- coding: utf-8 -*-

# @Time    : 2018/3/14 10:01
# @Author  : bearyang
# @Site    : 
# @File    : StringSort.py
# @Software: PyCharm
# Lintcode 830. 字符串排序
# http://www.lintcode.com/zh-cn/problem/string-sort/


class Solution:
    """
    @param str: the string that needs to be sorted
    @return: sorted string
    """
    def stringSort(self, str):
        map = {}
        for i in range(len(str)):
            if str[i] in map.keys():
                map[str[i]] = map.get(str[i]) + 1
            else:
                map[str[i]] = 1
        keylist = list(map.keys())
        keylist.sort()

        def fre(x):
            return map.get(x)

        keylist.sort(key=fre, reverse=True)
        str = ''
        for ch in keylist:
            for i in range(map.get(ch)):
                str = str + ch
        return str


test = Solution()
# str = 'bloomberg'
str = 'dmlqnpuvslpxvgjpobfvmlqsfbcftlzcnflgluuixccixbihebugejzwowgmgxcrsdypjhpytwmorxcupeozxzknxobhpatqjbqqgjfxwijqmhdaooieqgyqznyurgjrwawfyfshaphnmbxhsckjkbaitystixpbomwuulsecffvkdobwpoiyiebtudddjxupvqbthntrruqecuvnpsrbakvoziztkhyxyarycjjvgstrlzgwygrzkggwwglycgrpegnmteccsgeznnanhaxnkqdnirjzdxwkmcdgpucdcyvzmirtbivrjjrmlelurcyguuptojhvukgwistzhqdufhoattamlgjxvbpjruaiwsosrqngtpmijmmrborjqlzugzihfjtxwccscomjvduhsjhrgizihrctjfuroyivjqgaxcenbffnaawblrpuoqlrxwjgblkvhugbcqvzbemhgnhngyashqfdemugiiagipwtqknjlsjfdcgedddzhhqurvacvdaijbfnnkzqhfjdzkiukddrbnkjrqbnxgqbdvacucfwjaezgbcznwxtmmhxqgzbqefweqnjkndonquqahspmmnbidmpodhdsvnnpgyvdheoydibyhgqvnhanezziwzlxbcnzttlykvalqmhmxalmldqzvmgxlroyiotsezeyucwptulspfljjgqmkuawkhoicguvuacerxnmwtzllklwglnabntwbocbdrrjjsoihdhkxfzcpkplikfvcqalwitsnlbisgdmmiooecelsmmwudntfhurbdgqoebentovsuynndkylsbssedurytdapyjqqnogpoamxmmhmsmeehayikncgnwairskiozdagfumejcqvmmvhbmlcxspbnxjedkgnmgivxjmavpjwvhyvputgfbcjcoblfgspevxwvihabvpqqvrieepnlzjchytabkmxdevrvfzfjortdyusrbuyfgitwjzgnegcnmefskubkmtsumqhzfwiwamtblxeoopjlpuezchtshgxgnnygbvftrhjklgfhconkjpuuxqxjzyzighmnkasfhbuwekwqfseegrkayxsqfbmphlwnmjvpflbyqxrvxhvqijjevjxpdobptjbydifxjqeheimvwroxrinmhjdutxjihbdrejyfknetalsekqtxrmxccbpjuwgivkijgdrgzagbwphcnbvtjplrifsxgkavbqropprjpxfrewaplppsomssbwbxvesnluezmrkatkikoaiykqzgctkepsoxzbkaziwuzvdpzjejuiltgaerskuyzxewjdvouuwmatcxcfussmlrvjmeshbybrqhvcgvsdrexucslafqknvjiqiswlxmurzupaumdlokwodsesgfrtlebqumkjwnlisqkbuofwtrvnsdixbcliuawxpvshniuearckxiqhpeomgknqvawbvrbtaxhnwftnuarowectkbzccaldvpuafcaowctnefijaupcscpkbgnlttjysihfzkrewzfawhtvrbejjftkqrgprvvkfmdvggsuipqbrtzfdctfgwmjicnvlukybnsuviitpeqyezclqgnmkttbcxvvxtgwbebcfdbfdvvneabqndowazixgybpwygitwmekidaetlyqfwyddzaxzuetletgxuvsrhqhjitvkaonzmyixsnaegobseconidxbargquedltdhrtbuwnhygulpkqvfjoezlzdtihbapalfjqcgzgidtobhkzyvrwpbsiavmvrmeatovffmjhbecnzytxtnrpoofpbjzeasydctursfauuzusyprberaqvrfeeznzmmiugdbutjkrjigdcvpzayqrlhkhnviegztxlxbjkgwtqmibztbjbebfkrkpvkoaztowheeajkpeqafkhvgzpijewniefqsmreyqwxqfofxksqjkbezmhjlsamtiisfsmnptgspetcjdmijxfqmeqcippbdthbcgqhjkvotpgeidupabxwqauggzzrdjrgkfkwrxdnkaiqikcfoiywxjdbahsxecnwlsykszcbhbasmgbtwnkhahqynnsigeeytnsewmkhrxdzziabeyegkuxhnsipnmxtwrzmcmumjahmfdgxbaxebgcrjnkcscgnswdhdkxwxgmgnbufcukiwxhgbomehwzfokxqpnruozdkfdnlnmtgmmnzktnigweerxpqxrewuzmckhkazcwftabdbqhbvwcnpzdmarfzyqlnbpintnngtpvmcdpqbmizbeohsxuvnylponoetgucjypzaqkqemsdgiukzenrdffrsmwwifxwjxdwdjlcxkamoaqlimgstclldeqztfubfoayitcbvqgjyqolsokhxlbqswvzaqogljqnqmyjjzhbahgdsjsbqvnbkzbvdqqioijcxygbbbdsnczqpnwunnzxbrmevfsaanseodmtlhmrcjrvxxkvofklczvujtsaexaiujcbtytvtecpidwvkldpasmaeglbbuzdjgrytjxzpurpvaxnsqssntskpilisjbrospldrgmpukvbuqimdzfontmaxiqfzdfcixabgogvmfqgvhdlspvmojvvydqyiphxexklnjsjtfenputniilfxzbdfkpbudqmdvvnaxmitiylmpvfhaowqpqzxzoehrgbssogcmftqlmcojyungnatlwdxxpxtagnxcfxjchtwitddeykycxlqaqsfgdxvjttefldktblftagwwkkcydlnmivrftbhajrebjushsxjztorihfdtrvsdrggcykbjfwwjsydqrhkipkehixylggtqneixbmngzpqabwcahurfkevnoyfldngnpievjtxesujiyhltcdsebzoouubhngqpgousrcnpebpzybfedwedeovsnvxntjtahslgiqnlktgdjbuiaeavyrcjsxjeewiifrzexqdtrtmzqmdoawaaedthownkvfoogogsgfvyumtofursfuuqvroencxigerepyusyhuqcvvzfqpqmfbqcdwgenfawrvhizkhiiqtxemzvlejkqguvqztchgmpixrkqcetboiyvkzjxyrjpfgfqfbiwfnklhwrkrrqxfppfigknesybpzxsepneilztknefeauwqctzehqyxbzfkymhkyfksosfacwifqkvafynyzwijexzirkplstldhpwwrohdbkltzboeqwjpkihzillljlmzohamxrlfxtoirldmalijdruhzbthiulixwdytdjsubgqfmaqggeznbtugusrhoovdqwuutzlnekfbnqgsmwotjdsaxxbmqmuihqqcohqsltoxksbqotopcwoekwtvfkebcezrlycxlwjcqsvnetsaqqkugwnjqyfknojhhqheseuyvsypbywkevbqxmpnodejkfncbpptufvfwxmdtprnpryffqrztwvvpgaisxcnclhawstpvnvwegjnxghpylcchburjxmlifqccibtnyynngcyskkfsxswcfbvjqbanoztdwawujaumrspuxcgefkgtazuqkvcwmnvbeoqbbxpzpmdvdqbarqvqcskpjizoemndkfnkwgbycafqstygktxewtnhffawxkfndwiydvrweffpjflortyooudxyoltnlpswxlnydtbhfrfruaiogczohpgkykojtpylfwcuizsewhbknadbwzceemhjoybqlaknnkhanmpqqraehvlrvoevxihdtnraebvfnqlmseujxlvcyrfjjsywifiyyoykusnvhyhzrjsglrlwxjzqqpwzdwjofvtvezpyusggjcoaglrmwsrumxbpmfybxocnsktvioxnuhyvjnrkhkljzhslhefrhqhwqmiscqcwduamskyjcbpvgbspsxbvjhqngjmfmsuxkihvojbujxwfzjceqbdksusnahwjxqxacarjedztykfrognojbbnwzhvgpltxozvbvjpsmlanyxrxekyldvkjyonrcisyypelwubchuvhxackrfruvifrauqlagnnkkpskfqtgfvcvdaysbzoxixrfpfprdoqndygevncleokqnsaaohqsaprrdqikkdawdxedjgpsombanpyusurpyyuyramdtzjfsobomtpgzmlcuhvnkgpdoklhmjpidlsymhjrqpmeuzitwpdqdxztjrwnioldqfxagxpgwbopbxkzucqgpgzgizduvfunpsqjendrdslanaseerkuqevzbecagztlhzjlbolxynbcrrldfovhdefnmibprlqnucscmulvikqptqjohzpdsfrbmjwotxnvteuvstprwzarqvprrpqmyjftlvbezsilsgstuwudbhugyulawpzwxayzomttedjiemqqcaipgxqzuezafhmybrcsixcrxpemlyxsbhkqkfrswmlujiinuzsocvmuuqbjavppwirwzwkxzafymhmtiuthvfzhckckaxaisevzyftxasesfejqgvtazthypwnikymcvwmcygmbfyoqvismvhyvnlslbtlltmpnhsqekkepkfmbdsbccewyrkorxtqpdiaxkevvriujuxxsviludlhoqzbhcrbzdavkgzanycgkhgdfnxdcjdceswwrtmxzhlpeaeyccvdmcjcuhcpnpmxwuwthrabhssnevoxebwxlqusfdpswchfyrsytcievitrvbdorkzkhekvnsumllcqircnrcfwcivuhnmlpogczhiqukutoqchvzfivobkxltzuhfoqwebsiuxmoqtssmihjmjlylfqhvhhvyhqnejkqjtwsbiltmwawzcllahxqypintynqtsbagyasertgrxrixmxckzqhjzzndgweplbgsfxebmatfecmjvxepnqmaihmwrwjqmpnxmoyuotvvbujncscqfjsgoggeojyaurbfnongqnlqvfcofhqeflixvzowczvfyxgdfzmeisqiuhugtupounzcjmbnlbhtumramfcasulumzkgwzvmqksayznptvsewpvlnilripkjdvvplnrqiiibahebutjqzqusyfcgekyhhwlhwctwxpaeromaawdbwpalmjapdjihkynvgekaloqtqcbeeqkqrjesrpewbwvygxgtrylaqddvnwwqdftitwejxhhibouyiarawcyoumljjtzlteaqcmhoganmbkoqyvtnlausxjsdvqttnhiekrqfkcxfkoitwahecfnoylxwblqgdpxppgyscpbkewvniysgjpeiabzxbgovjuwbpgktwieheqqusxysgnbinbaiqrinnsayibvtkpiuyvbnotuennfmmxqyxerfjowoqfwbfscensjvephhujlndjmmkenhlkhmsgnmpvzivmxtamaimkgaesgaodgrmxhaqnbyzbshfcujbudhbafslyzbthrvwldoovzjqvwxlkdlxraehtxnonezzoiqrcxtmlskelhwlmdvntxswusfzwybirawxbbgwmlgedqeziblwioweeplhsgyawslvkklqfbiobvbxanptcsjnsaimjzgbzbgwtvjerxsvqcppzertlponnvutjwcrtcvlaxbtthgnfatvukvqdqdvqnslnoikfotfshxwwywacyyycsnxcwwhcjryxpddjypqgbhvcgeevglyzoixymwcaqxoxikqjmppsnilhmwzwqidzormshudrtbptcabarsearbosmavgralzedfhyumbuijgadcunnvruryvwwkrfdcsxeepihzyuktxxbxhkjopinraoybjvwirrshqfkqwaexuqhkdzcnklbnordydtwhiyqwngxfsrqlvkejlduovhlvdxqtdnzvjovcwhhjxsdbyhxjkqslctexvckqaaoboqwfflicxcyhgeciqsftlbrsldhdlfbjrfzqaspzqqtvpoklfayifampqgxarmrukuczsgdqkjplpekipwxbngciusnvkddlzefhydoqzudbnhkmzpmxaoaprgcwctxwpbnqisrdmnjdwikskatwwbccfgfzlcwttnzkkljiobbwostkygyefaxtsuwlabvjddqiycuhplhwnqkrdwhmfiqzfvrqqxgnbdbppzodbazimhjxxtbxuavdpdauursnckgztnxytfjxzrtkxgttpjtrmttxesremjhzgxsdlvlqwjvpjbslmppgwgsvbeuonrafgynglbrapmaqtfcdfjrwelvctcuvqlhlfxybqnlvdrifcxqfohnlsrugqcrbderhucqkycyedffmmouvkxmhavzunbigetrlgdepsnxivvljavbfsedgpcdscjquocvlufedknnlzgqzchwniddxfbhoppnatejxwsgnomesjaauyzjxqesalswggyhcgshhodlhvsvvgwyfbgtmajqkjkooutwbntagdbawxzmqidhsrpuyjhvgbgvkirecomycxtsihpetzacqbmlahcheszummmfrgsfsqwmtzxorkqnpjcdlwlsiaewymfzafsgdlwidfpiwgyszzuctvpegzaedwckfucotssqmmcxlfvwaolfserpskwedzbesnfvyjidkqppxliczcmbluslhhzivghjgwtarxneorxpwluzsbqunwfteoewapnnuggmvnzwchzmertpkgclefjqzafmcglckrllmhfnphcuztoyyaslxdetnnnmvztlbbzjbvkzogzgthweiurwugloiibqgvkzzpsfetealekzzuelcpawzmjemxseqwmjubikxwrqsnkrytxtwmawuxfztqngbgqjinoxuiurjdnoeeyickmrrjonnuedkwubmwevfdlhgxbbobwitcdkwclwfbsapmkoqcpuqgnwyyfkeiblstexdbpnbuhwmlbprgjisxtqlskxwssgjjezrjvgkhedhssypomcdneablygqlssfqkdsygffkxvcoluxoepmqxxilhmybscmswflaerawtfdjwwvhlveutcwdqncxjsiuxcvykbbvdospgilfcbzyzdvtfoveuwfgagwqtxcvsvigzjidwofiuejdnmpiappuyamouubvryfpicbdiyqrymqsymvtywggydptsxrre'
print(test.stringSort(str))
